DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('patient/', include('patient.urls'))
]

common/urls.py
from django.urls import path
from . import views
from .views import ThankYouView,UserCreateView, UserListView, LoginView, LogoutView
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns= [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),  # path는 Home_view를 함수로 예상함
    path('create_user/', UserCreateView.as_view(), name='create_user'),
    path('list_user/',UserListView.as_view(), name='list_user')
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns= [
    path('list/', views.patient_list, name='list'),
    path('add/', views.patient_add, name='add'),
    path('patient_common/',views.patient_common, name='patient_common'),
    path('patient_detail/<int:pk>', views.patient_detail, name='patient_detail'),
    path('patient_detail/search/', views.search_results, name='search_results'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=300, null=False)
    is_login = models.BooleanField(default=False)
    HOSPITAL_CHOICES = (
        ('SEOUL','서울대학병원'),
        ('INHA', '인하대학병원'),
        ('YONSEI', '연세세브란스병원')
    )

    hospital = models.CharField(max_length=10, choices=HOSPITAL_CHOICES, default='INHA')

patient/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    #patient_img = models.ImageField()
    latest_diagnosis = models.DateField()
    birthday = models.DateField()
    patient_num = models.IntegerField()
    def __str__(self):
        return f"{self.last_name}, {self.first_name}, {self.patient_num}"
    

common/forms.py
from django import forms
from django.contrib.auth.hashers import check_password, make_password # 비밀번호 저장시 make_password이용(hash값)
from .models import CustomUser as User

class CustomUserForm(forms.ModelForm):
    # hospital 필드를 ChoiceField로 정의
    hospital = forms.ChoiceField(choices=User.HOSPITAL_CHOICES,
                                 widget=forms.Select(attrs={'class': 'custom-select'}))
    class Meta:
        model = User
        fields = ['username', 'password', 'hospital']

class LoginForm(forms.Form):
    username = forms.CharField(
        error_messages={
            'required': '아이디를 입력하세요'
        },
        max_length=20,
        label='아이디',
    )
    password = forms.CharField(
        error_messages={
            'required': '비밀번호를 입력하세요'
        },
        widget=forms.PasswordInput,
        label='비밀번호'
    )

    def clean(self):  # validation을 진행하는 메서드
        cleaned_data = super().clean()  # 부모 클래스에서 갖고 있던 clean을 상속 받아요.
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if password and username:  # 비밀번호 입력란 2개가 입력되어야하고
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                self.add_error('username', '해당 아이디가 없습니다.')
                return
            if not password == user.password:  # 좌항은 사용자 입력값, 우항은 db에 있는값(hash값으로 저장된 비밀번호) 둘을 서로 비교해줘요.
                self.add_error('password', '비밀번호가 틀렸습니다.')

            else: #로그인이 진행되는 경우
                self.username = user.username  # db에서 가져온 정보를 username에 할당
                user.is_login=True
                user.save()
                print(user.is_login)

patient/forms.py
from django import forms
from .models import Patient
from django.forms import ModelForm

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['patient_num','first_name','last_name','birthday', 'latest_diagnosis']
        widgets = {
            'latest_diagnosis': forms.DateInput(attrs={'type': 'date'}),
            'birthday': forms.DateInput(attrs={'type': 'date'}),

        }
         

DjangoApp/views.py
from django.shortcuts import render,redirect
from django.conf import settings

def home(request):
    # 홈페이지 뷰 로직
    if settings.IS_NOW_LOGIN: #true일 경우
        return redirect('patient:list')
        print("login completed!")
    else:
        return redirect('common:login')
        print("not login")

common/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView,CreateView, ListView, FormView
from .models import CustomUser
from .forms import LoginForm
from .forms import CustomUserForm
from django.conf import settings
class ThankYouView(TemplateView):
    template_name = "common/thank_you.html"

class UserCreateView(CreateView):
    model = CustomUser
    form_class = CustomUserForm  # 위에서 정의한 폼 클래스 사용
    success_url = reverse_lazy("common:login")

class UserListView(ListView):
    #model_list.html을 자동으로 찾음
    model = CustomUser
def LogoutView(request):
    # 홈페이지 뷰 로직
    now_user = settings.GLOBAL_LOGIN_USER
    user = CustomUser.objects.get(username=now_user)
    user.is_login = False
    user.save()
    settings.IS_NOW_LOGIN = False
    return redirect(reverse('home'))

class LoginView(FormView):
    template_name = 'common/login.html'
    form_class = LoginForm
    success_url = reverse_lazy("home")

    # LoginView.as_view()가 실행될 때
    def form_valid(self, form):
        self.request.session['user'] = form.username
        settings.GLOBAL_LOGIN_USER = form.username
        settings.IS_NOW_LOGIN = True
        return super().form_valid(form)

patient/views.py
# Create your views here.
from django.shortcuts import render,redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
from .forms import PatientForm
from . import models
from django.conf import settings
import os
def patient_add(request):

    if request.method =='POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.cleaned_data)
            return redirect(reverse('patient:list'))
    else:
        form  = PatientForm()
    return render(request, 'patient/add.html', context={'form':form})


def patient_list(request):
    all_patient = models.Patient.objects.all()
    context = {'patient': all_patient}

    if request.method == 'POST':
        # POST 요청 처리
        patient_number = request.POST.get('patient_number')  # 환자 번호 가져오기
        try:
            patient_to_delete = models.Patient.objects.get(patient_num=patient_number)
            patient_to_delete.delete()
            print(patient_to_delete)
        except models.Patient.DoesNotExist:
            pass  # 환자가 없으면 무시

    return render(request, 'patient/list.html', context=context)

def patient_common(request):
    return render(request, 'patient/patient_common.html')

def patient_detail(request, pk):
    patient = get_object_or_404(models.Patient, pk=pk)
    #해당하는 object를 template에 보내줌
    error_message = None
    #사용자가 nii file을 업로드할 경우
    if request.method == 'POST':
        if 'formFile' in request.FILES:
            uploaded_file = request.FILES['formFile']
            file_name = uploaded_file.name

            # 저장 경로를 설정
            save_path = os.path.join(settings.MEDIA_ROOT, 'uploaded_files', file_name)

            # 디렉터리가 존재하지 않으면 생성
            os.makedirs(os.path.dirname(save_path), exist_ok=True)

            with open(save_path, 'wb') as destination:
                for chunk in uploaded_file.chunks():
                    destination.write(chunk)
            print(file_name, "uploaded!")

        else:
            error_message = "파일을 선택해 주세요"
    return render(request, 'patient/patient_detail.html', {'patient': patient, 'error_message': error_message})


def search_results(request):
    query = request.GET.get('q')
    results = models.Patient.objects.filter(first_name__icontains=query)  # 검색 로직을 수정하세요

    return render(request, 'patient/search_results.html', {'results': results, 'query': query})

common/templates/common/customuser_form.html
{% extends "home.html" %}
{% block content %}
<!-- 제목 field-->
<div class="input-form col-md-12 mx-auto">
    <div class="row mt-5">
      <div class="col-12 text-center">
        <h1>Sign up</h1>
        </div>
    </div>
<!--이하 form field -->
    <div class="row mt-5">
    <div class="col-12">
        <form method="post">
                {% csrf_token %}
            <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
                <label for="{{ form.username.id_for_label }}" style="display: block;">{{ form.username.label_tag }}</label>
                <input type="{{ form.username.field.widget.input_type }}" class="form-control" id="{{ form.username.id_for_label }}"
                    placeholder="{{ form.username.label }}" name="{{ form.username.name }}" style="width: 100%">
                <br>
                <label for="{{ form.password.id_for_label }}"  style="display: block;">{{ form.password.label_tag }}</label>
                <input type="{{ form.password.field.widget.input_type }}" class="form-control" id="{{ form.password.id_for_label }}"
                    placeholder="{{ form.password.label }}" name="{{ form.password.name }}" />
            </div>

            <!-- hospital field-->
            <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
                <label for="{{ form.hospital.id_for_label }}" style="display: block;">{{ form.hospital.label_tag }}</label>
                <select id="{{ form.hospital.id_for_label }}" name="{{ form.hospital.name }}" class="custom-select">
                    <option value="" selected>---------</option> <!-- 추가된 부분 -->
                    {% for value, label in form.hospital.field.choices %}
                        <option value="{{ value }}">{{ label }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- button field-->
            <div class="mb-3 text-center" style="max-width: 300px; margin: 0 auto;">
            <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    </div>
</div>

{% endblock %}

common/templates/common/customuser_list.html
{% extends "home.html" %}
{%  block content %}
<h1>List of Users (ListView)</h1>
<ul>
    {% for user in object_list %}
        <li>
        {{user.username}} {{user.password}} {{ user.hospital }} {{ user.is_login }}
        </li>
    {% endfor %}
</ul>
{% endblock %}

common/templates/common/login.html
{% extends "home.html" %}
{% load static %}

{% block content %}
    <style>
        .container-fluid.p-0 {
            padding-top: 60px; /* Navbar의 높이와 동일한 값으로 설정 */
        }
        .grid-container {
            height: calc(100vh - 60px); /* 화면 높이에서 Navbar 높이를 뺀 높이를 설정 */
        }
        .center-content {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>

    <div class="container-fluid p-0">
        <div class="row" style="padding: 0;">
            <div class="col-md-8 grid-container" style="padding: 0;">
                <!-- 첫 번째 그리드에 이미지를 추가하세요 -->
                <img id="randomImage" class="fluid" alt="이미지 설명"
                    style="width: 100%; height: 100%; object-fit: cover;">

            </div>
            <div class="col-md-4 grid-container">
                <div class="d-flex flex-column justify-content-center align-items-center" style="height: 100%;">
                    <!--brain icon-->
                    <div class="row mt-3 center-content">
                        <div class="col-12 text-center">
                            <img src="{% static '/images/brain.png' %}" style="width:130px" alt="이미지 설명">
                        </div>
                    </div>

                    <!-- sign-in text -->
                    <div class="row mt-3 center-content">
                        <div class="col-12 text-center">
                            <h1>Sign in</h1>
                        </div>
                    </div>
                    <div class="row mt-3 center-content">
                        <div class="col-12">
                            {{ error }}
                        </div>
                    </div>

                    <!-- 로그인 입력 폼 -->
                    <div class="row mt-3 center-content">
                        <div class="col-12">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <!-- 아이디 입력 -->
                                <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
                                    <label for="id_username">Username</label>
                                    <input type="text" class="form-control" id="id_username" name="username"/>
                                </div>

                                <!-- 비밀번호 입력 -->
                                <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
                                    <label for="id_password">Password</label>
                                    <input type="password" class="form-control" id="id_password" name="password"/>
                                </div>

                                <!-- button field -->
                                <div class="mb-3 text-center" style="max-width: 300px; margin: 0 auto;">
                                    <button type="submit" class="btn btn-primary">Sign in</button>
                                </div>
                                <p class="text-center">Don't have an account? <a href="{% url 'common:create_user' %}">Join
                                    Now</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- 이미지 랜덤 호출-->
<!-- 이미지 요소 -->
<img id="randomImage" class="fluid" alt="이미지 설명"
     style="width: 100%; height: 100%; object-fit: cover;">

<script>
    // 이미지 파일 목록을 JavaScript 배열로 저장
    var imageFiles = [
        '{% static "images/bg/bg_1.jpg" %}',
        '{% static "images/bg/bg_5.jpg" %}',
        '{% static "images/bg/bg_6.jpg" %}',
        '{% static "images/bg/bg_8.jpg" %}',
        // 추가 이미지 경로들을 여기에 추가하세요
    ];

    var imageElement = document.getElementById('randomImage');
    // 페이지 로드 시 초기 랜덤 이미지 설정
    var initialRandomIndex = Math.floor(Math.random() * imageFiles.length);
    var initialRandomImagePath = imageFiles[initialRandomIndex];
    imageElement.src = initialRandomImagePath;

</script>

{% endblock %}

common/templates/common/thank_you.html
{% extends "home.html" %}

{% block content %}
    <h1>login completed</h1>
{% endblock %}

patient/templates/patient/add.html
{% extends "home.html" %}
{% block content %}
<div class="input-form col-md-12 mx-auto">
    <div class="row mt-5">
        <div class="col-12 text-center">
             <h1>Add Patient</h1>
        </div>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
            {% for field in form %}
                <label for="{{ field.id_for_label }}" style="display: block;">{{ field.label_tag }}</label>
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                    placeholder="{{ field.label }}" name="{{ field.name }}" style="width: 100%">
                <br>
            {% endfor %}
        </div>
        <div class="mb-3 text-center" style="max-width: 300px; margin: 0 auto;">
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

patient/templates/patient/list.html
{% extends "home.html" %} {% block content %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>환자 목록</h1>
    <h4>진료 기록 조회를 위해 <u>환자 코드</u>를 클릭해 주세요.</h4>
  </div>
</div>
<br />

<!--Patient add button-->
<div class="mb-3 text-center" style="text-align: center">
  <a href="{% url 'patient:add' %}" class="btn btn-primary">환자 추가</a>

  {% include "./modal.html" %}
</div>
{% include "./search_form.html" %}

<!-- Patient List Field-->
{% csrf_token%}
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">환자 코드</th>
      <th scope="col">이름</th>
      <th scope="col">생년 월일</th>
      <th scope="col">최근 진료일</th>
    </tr>
  </thead>
  <tbody>
    {% for person in patient%}
    <tr>
      <th scope="row">{{ person.id }}</th>
      <td>
        <a
          class="patient-link"
          href="{% url 'patient:patient_detail' pk=person.id %}"
          ><b><u>{{ person.patient_num }}</u></b></a
        >
      </td>
      <td>{{ person.last_name }} {{ person.first_name }}</td>
      <td>{{ person.birthday }}</td>
      <td>{{ person.latest_diagnosis }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

patient/templates/patient/modal.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#delete_Modal">
  목록 삭제
</button>

<!-- Modal -->
<div class="modal fade" id="delete_Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Patient</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3" style="max-width: 300px; margin: 0 auto;">
                <label for="numberInput">Patient Number to DELETE:</label>
                <input type="number" id="numberInput" name="patient_number" class="form-control" style="width: 100%">
            </div>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

patient/templates/patient/patient_common.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <!-- Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    <title>Hello, brain!</title>

    <style>
      /* 버튼 컨테이너 스타일을 지정합니다. */
      .button-container {
        display: flex;
        flex-direction: row; /* 버튼을 가로로 나열합니다. */
        align-items: center; /* 버튼을 세로 방향으로 가운데 정렬합니다. */
        margin-top: 10px; /* 버튼과 이미지 사이의 간격을 조정할 수 있습니다. */
      }

      /* 버튼 스타일을 지정합니다. */
      button {
        margin-right: 10px; /* 버튼 사이의 간격을 조정할 수 있습니다. */
      }
      /* 이미지 스타일을 지정하여 크기를 50x50 픽셀로 설정합니다. */
      #gifImage {
        width: 500px;
        height: 500px;
      }
    </style>
  </head>
  <body>
    <!-- 네비게이션 바 -->
    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    <div class="row mt-5">
      <div class="col-12 text-center">
        <h1>Detail for "~"</h1>
        </div>
    </div>
    <!-- GIF 이미지 추가 -->
    <img id="gifImage" src="https://i.gifer.com/JPFn.gif" alt="기본 이미지" class="rounded mx-auto d-block"/>

    <!-- 버튼 컨테이너 추가 -->
    <div class="mb-3 text-center" style="max-width: 300px; margin: 0 auto;">
    <div class="button-container">
      <!-- 버튼 추가 -->
      <button id="playGif1" class="btn btn-primary">T1</button>
      <button id="playGif2" class="btn btn-primary">T2</button>
      <button id="playGif3" class="btn btn-info">FLAIR</button>
      <button id="playGif4" class="btn btn-info">Tumor</button>
    </div>
    </div>

    <!-- JavaScript 코드 추가 -->
    <script>
      var gifPaths = [
        "https://i.gifer.com/JPFn.gif",
        "https://lab.hanium.or.kr/23_HF114/23_HF114/-/raw/main/images/output.gif",
        "https://upload.wikimedia.org/wikipedia/commons/9/9e/Brainanim.gif",
        "https://i.pinimg.com/originals/fd/3c/cd/fd3ccd7b49e366b4206f5ac7f8fa8dac.gif",
      ];
      var gifImage = document.getElementById("gifImage");
      var buttons = [
        document.getElementById("playGif1"),
        document.getElementById("playGif2"),
        document.getElementById("playGif3"),
      ];

      // 버튼 클릭 시 해당 GIF 재생
      for (var i = 0; i < buttons.length; i++) {
        buttons[i].addEventListener(
          "click",
          (function (index) {
            return function () {
              gifImage.src = gifPaths[index];
            };
          })(i)
        );
      }
    </script>

    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
  </body>
</html>

patient/templates/patient/patient_detail.html
{% extends "home.html" %} {% load static %} {% block content %}
<style>
  .container-fluid.p-0 {
    padding-top: 60px; /* Navbar의 높이와 동일한 값으로 설정 */
  }
  .grid-container {
    height: calc(100vh - 60px); /* 화면 높이에서 Navbar 높이를 뺀 높이를 설정 */
    width: 100%;
  }
  .center-content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
</style>

<div class="container-fluid no-gutters">
  <div class="row" style="padding: 0">
    <div class="col-md-8 grid-container" >
      <!-- 첫 번째 그리드 -->
      <img id="image-display" src="{% static 'images/notice.png' %}" style="width: 90%; height: 90%" alt="Image"/>
        <div id="myDiv" style="display:none;">

            <div class="card" style="width: 100%;">
              <div  class="card" style="width: 100%;">
              <div class="card-body">
                <h3 class="card-title">예상 수명 기간</h3>
                <p class="card-text">dignosis: training dataset에 기반한 환자의 생존 예측기간은 1283days 입니다.</div></p>
              </div >
            </div>
        </div>


    </div>
    <div class="col-md-4 grid-container" >
      <!-- 두 번째 그리드 -->
      {% include './patient_detail_info.html' %}
    </div>
  </div>
</div>
{% endblock %}

patient/templates/patient/search_form.html
<!-- search_form.html -->
<form
  method="get"
  action="{% url 'patient:search_results' %}"
  style="margin-bottom: 10px; margin-left: 10px"
>
  <input type="text" name="q" placeholder="검색어 입력" />
  <button type="submit">검색</button>
</form>

patient/templates/patient/search_results.html
{% extends 'home.html' %} {% load static %} {% block content %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>환자 조회 결과</h1>
    <!-- 이 부분은 필요에 따라 디자인을 추가하세요 -->
  </div>
</div>
<br />

<!-- 검색 결과를 나타낼 테이블 -->
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">환자 코드</th>
      <th scope="col">이름</th>
      <th scope="col">생년 월일</th>
      <th scope="col">최근 진료일</th>
    </tr>
  </thead>
  <tbody>
    {% for person in results %}
    <tr>
      <th scope="row">{{ person.id }}</th>
      <td>
        <a
          class="patient-link"
          href="{% url 'patient:patient_detail' pk=person.id %}"
        >
          {{ person.patient_num }}
        </a>
      </td>
      <td>{{ person.last_name }} {{ person.first_name }}</td>
      <td>{{ person.birthday }}</td>
      <td>{{ person.latest_diagnosis }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="6">검색 결과가 없습니다.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/carousel.html
{% load static %}
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="5000">
      <img src="{% static 'images/brain_1.jpeg' %}" class="d-block mx-auto" style="height: 33vh" alt="...">
    </div>
    <div class="carousel-item" data-bs-interval="5000">
      <img src="{% static 'images/brain_2.jpeg' %}" class="d-block mx-auto" style="height: 33vh" alt="...">
    </div>
    <div class="carousel-item" data-bs-interval="5000">
      <img src="{% static 'images/brain_3.png' %}" class="d-block mx-auto" style="height: 33vh" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

templates/home.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Hello, brain!</title>
</head>
<body>
<!-- 네비게이션 바 -->
{% include "navbar.html" %}

{% block content %}

{% endblock %}

</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
{% load static %}
{% load templatetag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <img src="{% static 'images/brain.png' %}" style="width:30px" alt="이미지 설명">
        <span style="margin-right: 8px;"></span> <!-- 공백 추가 -->
        <a class="navbar-brand" href="{% url 'home' %}">BTdS  </a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "common:create_user" %}">회원가입</a>
                </li>
                <li class="nav-item">
                   {% is_user_logged_in as user_logged_in %}  <!-- is_user_logged_in을 변수 user_logged_in에 할당 -->
                    {% if user_logged_in %}
                        <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if user_logged_in %}
                        <a class="nav-link" href="{% url "patient:list" %}">환자</a>
                    {% else %}
                        <a class="nav-link" onclick="alert('로그인을 해주세요')" href="{% url "common:login" %}">환자</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>